# Generated by Django 4.0.4 on 2022-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.IntegerField(unique=True)),
                ('score', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
