# Generated by Django 4.0.4 on 2022-04-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='score',
            field=models.FloatField(),
        ),
    ]
