# Generated by Django 4.0.4 on 2022-04-23 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 11, 52, 15, 759202, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 11, 52, 15, 759508, tzinfo=utc)),
        ),
    ]
