# Generated by Django 4.0.4 on 2022-04-25 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_student_created_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 15, 41, 58, 93025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 15, 41, 58, 93298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 15, 41, 58, 93025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 15, 41, 58, 93298, tzinfo=utc)),
        ),
    ]
